import React from "react";
import Geniric from "../Pages/Geniric";
export const navbar = [
  {
    id: 1,
    title: "Home",
    path: "/home",
    Element: <Geniric />,
    search: "?",
    hidden: false,
    private: false,
  },
  {
    id: 2,
    title: "Properties",
    path: "/properties",
    Element: <Geniric />,
    search: "?",
    hidden: false,
    private: false,
  },
  {
    id: "2-1",
    title: "Properties",
    path: "/properties/:id",
    Element: <Geniric />,
    search: "?",
    hidden: true,
    private: false,
    param: true,
  },
  {
    id: 3,
    title: "Contacts",
    path: "/contacts",
    Element: <Geniric />,
    search: "?",
    hidden: false,
    private: false,
  },
  {
    id: 4,
    title: "SignIn",
    path: "/signin",
    Element: <Geniric />,
    search: "?",
    hidden: true,
    private: false,
    param: true,
  },
  {
    id: 5,
    title: "SignUp",
    path: "/signup",
    Element: <Geniric />,
    search: "?",
    hidden: true,
    private: false,
    param: true,
  },
  {
    id: 6,
    title: "MyProperties",
    path: "/profile/myproperties",
    Element: <Geniric />,
    search: "?",
    hidden: true,
    private: false,
    param: true,
  },
  {
    id: 7,
    title: "Add new house",
    path: "/profile/add",
    Element: <Geniric />,
    search: "?",
    hidden: true,
    private: false,
    param: true,
  },
];
