import { createContext, useState, useEffect } from "react";
import { NoImg } from "../assets/icons";
export const dressMainData = createContext();

export const DressMenu = ({ children }) => {
  const [dressInfo, setDressInfo] = useState({
    type: 5555,
    ClothesBorder: 1,
    PageSetModal: false,
    yandexOpenMenu: false,
    yandexOpenMarket: false,
    openMainMenu: true,
    yandexFullScreen: false,
    yandexOpenMarketLocation: false,
    yandexGetMarketId: null,
    // Cordinate
    yandexPositionX: null,
    yandexPositionY: null,
    yandexOpenRegionList: false,

    // Category
    openCategoryFilter: false,
    // Catalog
    openCatalogFilter: false,
    // Shop/:Id
    openShopIdFilter: false,
    // Catolog/:Id
    openCatologId: false,

    // colorFull
    BtnSeason: "",
    BtnOpacitySeason: "",
    BtnFocusSeason: "",
    ColorSeason: "",
    TextHoverSeason: "",
    TextColorSeason: "",
    LinkActiveSeason: "",
    BtnActiveSeason: "",
    AuthenActiveSeason: "",
    // BottomComponentProducts
    mainCardProducts: [],
    mainSearchName: null,
    mainRegionId: 2,
    mainSubRegionId: null,
    mainColorId: null,

    ProductList: [
      {
        id: 1,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfrous7hj8j9g698ann0/t_product_540_high.jpg#1677854670106",
        noProductImg: <NoImg />,
        title: "Футболка женская однотонная 100% хлопок, белая черная",
        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258 000",
        price: "372 000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 2,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfvjvm7hj8j9g698q1qg/t_product_540_high.jpg#1677854670118",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",
        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 3,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cee9lmov1htd23aj6gjg/t_product_540_high.jpg#1677855157929",
        noProductImg: <NoImg />,
        title: " Комплект мужской одежды Zero-Limited",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 4,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfh16dd40v9uauhi42hg/t_product_540_high.jpg#1677855222081",
        noProductImg: <NoImg />,
        title:
          "Базовая мужская однотонная футболка, 100% хлопок, мужская женская, белая, черная",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 5,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfmebc7hgiopn8lcdoh0/t_product_540_high.jpg#1677855264045",
        noProductImg: <NoImg />,
        title: "Футболка мужская Playowo",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 6,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf557s8l08k0o9qi31gg/t_product_540_high.jpg#1677855329602",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 7,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfmebc7hgiopn8lcdoh0/t_product_540_high.jpg#1677855264045",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 8,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf2h9jqvtie1lhbgt6mg/t_product_540_high.jpg#1677855329588",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 9,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf53ng0v1htd23al4sqg/t_product_540_high.jpg#1677855423341",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "15.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 10,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf5vfb2vtie1lhbh7h50/t_product_540_high.jpg#1677855423352",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 11,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf53ng0v1htd23al4sqg/t_product_540_high.jpg#1677855423341",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "",
        price: "75.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 12,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf8g3tivtie1lhbhf1p0/t_product_540_high.jpg#1677855423420",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 13,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfcdqlavtie1lhbhs490/t_product_540_high.jpg#1677855423521",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 14,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfmebc7hgiopn8lcdoh0/t_product_540_high.jpg#1677855264045",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "",
        price: "140.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 15,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfcdvh0l08k0o9qiqgcg/t_product_540_high.jpg#1677855423619",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 16,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfrous7hj8j9g698ann0/t_product_540_high.jpg#1677854670106",
        noProductImg: <NoImg />,
        title: "Футболка женская однотонная 100% хлопок, белая черная",
        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258 000",
        price: "372 000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 17,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfvjvm7hj8j9g698q1qg/t_product_540_high.jpg#1677854670118",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",
        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 18,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cee9lmov1htd23aj6gjg/t_product_540_high.jpg#1677855157929",
        noProductImg: <NoImg />,
        title: " Комплект мужской одежды Zero-Limited",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 19,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfh16dd40v9uauhi42hg/t_product_540_high.jpg#1677855222081",
        noProductImg: <NoImg />,
        title:
          "Базовая мужская однотонная футболка, 100% хлопок, мужская женская, белая, черная",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 20,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfmebc7hgiopn8lcdoh0/t_product_540_high.jpg#1677855264045",
        noProductImg: <NoImg />,
        title: "Футболка мужская Playowo",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 21,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf557s8l08k0o9qi31gg/t_product_540_high.jpg#1677855329602",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 22,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfmebc7hgiopn8lcdoh0/t_product_540_high.jpg#1677855264045",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 23,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf2h9jqvtie1lhbgt6mg/t_product_540_high.jpg#1677855329588",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 24,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf53ng0v1htd23al4sqg/t_product_540_high.jpg#1677855423341",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "15.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 25,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf5vfb2vtie1lhbh7h50/t_product_540_high.jpg#1677855423352",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 26,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf53ng0v1htd23al4sqg/t_product_540_high.jpg#1677855423341",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "",
        price: "75.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 27,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cf8g3tivtie1lhbhf1p0/t_product_540_high.jpg#1677855423420",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 28,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfcdqlavtie1lhbhs490/t_product_540_high.jpg#1677855423521",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "258.000",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 29,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfmebc7hgiopn8lcdoh0/t_product_540_high.jpg#1677855264045",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "",
        price: "140.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
      {
        id: 30,
        discount: "-30%",
        video: true,
        colourCard: false,
        diliver: true,
        like: true,
        buy: true,
        ProducImg:
          "https://images.uzum.uz/cfcdvh0l08k0o9qiqgcg/t_product_540_high.jpg#1677855423619",
        noProductImg: <NoImg />,
        title: "Line-Pattern Zipper Sweatshirt (Original Quality)",

        starCount: 256,
        shirtSize: "M | 3XL",
        sale: "",
        price: "372.000",
        saveFavourite: false,
        changeColor: [
          { id: 1, value: 1, action: false, colors: "bg-purple-700" },
          { id: 2, value: 2, action: false, colors: "bg-green-600" },
          { id: 3, value: 3, action: false, colors: "bg-red-700" },
          { id: 4, value: 4, action: false, colors: "bg-yellow-500" },
          { id: 5, value: 5, action: false, colors: "bg-black" },
          { id: 6, value: 6, action: false, colors: "bg-sky-500" },
        ],
      },
    ],
    // Market List
    MarketList: [
      {
        id: 1,
        marketId: 14301,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.343505, 69.247869],
      },
      {
        id: 2,
        marketId: 14302,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.304935, 69.235164],
      },
      {
        id: 3,
        marketId: 14303,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.344238, 69.242964],
      },
      {
        id: 4,
        marketId: 14304,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.323764, 69.359813],
      },
      {
        id: 5,
        marketId: 14305,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.341694, 69.420043],
      },
      {
        id: 6,
        marketId: 14306,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.321907, 69.254526],
      },
      {
        id: 7,
        marketId: 14307,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.320452, 69.219132],
      },
      {
        id: 8,
        marketId: 14308,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.307447, 69.249306],
      },
      {
        id: 9,
        marketId: 14309,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.292876, 69.261085],
      },
      {
        id: 10,
        marketId: 14310,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.32621, 69.248896],
      },
      {
        id: 11,
        marketId: 14311,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.318716, 69.248341],
      },
      {
        id: 12,
        marketId: 14312,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.282263, 69.216182],
      },
      {
        id: 13,
        marketId: 14313,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.337827, 69.22457],
      },
      {
        id: 14,
        marketId: 14314,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.327722, 69.213853],
      },
      {
        id: 15,
        marketId: 14315,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.311626, 69.207701],
      },
      {
        id: 16,
        marketId: 14316,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.318925, 69.312793],
      },
      {
        id: 17,
        marketId: 14317,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.326482, 69.334138],
      },
      {
        id: 18,
        marketId: 14318,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.31642, 69.230976],
      },
      {
        id: 19,
        marketId: 14319,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.309585, 69.267861],
      },
      {
        id: 20,
        marketId: 14320,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.314924, 69.245148],
      },
      {
        id: 21,
        marketId: 14321,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.30114, 69.220787],
      },
      {
        id: 22,
        marketId: 14322,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.325755, 69.28294],
      },
      {
        id: 23,
        marketId: 14323,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.317964, 69.295311],
      },
      {
        id: 24,
        marketId: 14324,
        accordion: false,
        address: "Ильинское-Усово (Московская область) Заповедная улица",
        workTime: "Ежедневно 08:00-22:00",
        star: "4.55",
        imgs: [{ id: 1, img: "" }],
        direction:
          'From the bus stop "LCD Usovo Park", cross the road. Opposite the Locals restaurant.',
        cordinate: [41.296016, 69.290532],
      },
    ],
  });
  const BtnSeasonArray = [
    {
      id: 1111,
      btn: "text-borderSummer bg-btnBgColor border-searchBgColor",
      btnOpacity: "text-borderSummer bg-opacity-10 bg-bgSummer",
      btnFocus:
        "focus:text-borderSummer focus:bg-btnBgColor focus:border-searchBgColor",
      textHover: "hover:text-borderSummer",
      textColor: "text-borderSummer",
      color: "#EAA700",
      btnActiveSeason:
        "text-borderSummer  bg-bgSummer border border-borderSummer",
      authenActiveSeason:
        "md:text-borderSummer bg-white bg-bgSummer md:border-borderSummer w-1/2  px-2 md:h-[48px] ss:h-[52px]  justify-center flex items-center bg-btnBgColor ss:border   rounded-lg",
      linkActive:
        "items-center justify-center bg-white rounded-lg md:h-[44px] text-sm md:w-[100px] md:mt-0 hidden md:flex border border-borderSummer text-borderSummer",
    },
    {
      id: 2222,
      btn: "text-borderAutumm bg-btnBgColor border-searchBgColor",
      btnOpacity: "text-borderAutumm bg-opacity-10 bg-bgAutumm",
      btnFocus:
        "focus:text-borderAutumm focus:bg-btnBgColor focus:border-searchBgColor",
      textHover: "hover:text-borderAutumm",
      textColor: "text-borderAutumm",
      color: "#E17A02",
      btnActiveSeason:
        "text-borderAutumm  bg-bgAutumm border border-borderAutumm ",
      authenActiveSeason:
        "md:text-borderAutumm bg-white bg-bgAutumm md:border-borderAutumm w-1/2  px-2 md:h-[48px] ss:h-[52px]  justify-center flex items-center bg-btnBgColor ss:border rounded-lg",
      linkActive:
        "items-center justify-center bg-white rounded-lg md:h-[44px] text-sm md:w-[100px] md:mt-0 hidden md:flex border border-borderAutumm text-borderAutumm",
    },
    {
      id: 3333,
      btn: "text-borderWinter bg-btnBgColor border-searchBgColor",
      btnOpacity: "text-borderWinter bg-opacity-10 bg-bgWinter",
      btnFocus:
        "focus:text-borderWinter focus:bg-btnBgColor focus:border-searchBgColor",
      textHover: "hover:text-borderWinter",
      textColor: "text-borderWinter",
      color: "#007DCA",
      btnActiveSeason:
        "text-borderWinter bg-bgWinter border border-borderWinter",
      authenActiveSeason:
        "md:text-borderWinter bg-white bg-bgWinter md:border-borderWinter w-1/2  px-2 md:h-[48px] ss:h-[52px]  justify-center flex items-center bg-btnBgColor ss:border rounded-lg",
      linkActive:
        "items-center justify-center bg-white rounded-lg md:h-[44px] text-sm md:w-[100px] md:mt-0 hidden md:flex border border-borderWinter text-borderWinter",
    },
    {
      id: 4444,
      btn: "text-borderSpring bg-btnBgColor border-searchBgColor",
      btnOpacity: "text-borderSpring bg-opacity-10 bg-bgSpring",
      btnFocus:
        "focus:text-borderSpring focus:bg-btnBgColor focus:border-searchBgColor",
      textHover: "hover:text-borderSpring",
      textColor: "text-borderSpring",
      color: "#008F0E",
      btnActiveSeason:
        "text-borderSpring  bg-bgSpring border border-borderSpring",
      authenActiveSeason:
        "md:text-borderSpring bg-white bg-bgSpring md:border-borderSpring w-1/2  px-2 md:h-[48px] ss:h-[52px]  justify-center flex items-center bg-btnBgColor ss:border   rounded-lg",
      linkActive:
        "items-center justify-center bg-white rounded-lg md:h-[44px] text-sm md:w-[100px] md:mt-0 hidden md:flex border border-borderSpring text-borderSpring",
    },
    {
      id: 5555,
      btn: "text-borderWinter bg-btnBgColor border-searchBgColor",
      btnOpacity: "text-borderWinter bg-opacity-10 bg-bgWinter",
      btnFocus:
        "focus:text-borderWinter focus:bg-btnBgColor focus:border-searchBgColor",
      textHover: "hover:text-borderWinter",
      textColor: "text-borderWinter",
      color: "#007DCA",
      btnActiveSeason:
        "text-borderWinter  bg-bgWinter border border-borderWinter",
      authenActiveSeason:
        "md:text-borderWinter bg-white bg-bgWinter md:border-borderWinter w-1/2  px-2 md:h-[48px] ss:h-[52px]  justify-center flex items-center bg-btnBgColor ss:border rounded-lg",
      linkActive:
        "items-center justify-center bg-white rounded-lg md:h-[44px] text-sm md:w-[100px] md:mt-0 hidden md:flex border border-borderWinter text-borderWinter",
    },
    
  ];

  useEffect(() => {
    BtnSeasonArray.filter((e) => e.id == dressInfo?.type).map((event) => {
      setDressInfo({
        ...dressInfo,
        BtnSeason: event?.btn,
        BtnOpacitySeason: event?.btnOpacity,
        BtnFocusSeason: event?.btnFocus,
        ColorSeason: event?.color,
        TextHoverSeason: event?.textHover,
        TextColorSeason: event?.textColor,
        LinkActiveSeason: event?.linkActive,
        BtnActiveSeason: event?.btnActiveSeason,
        AuthenActiveSeason: event?.authenActiveSeason,
      });
    });
  }, [dressInfo.type]);

  return (
    <dressMainData.Provider value={[dressInfo, setDressInfo]}>
      {children}
    </dressMainData.Provider>
  );
};
